import type { SimEvent } from './types'

/**
 * What-if SynapseFlow timeline — Nova has $25k authority and advances
 * before Sentinel can intervene. Cautionary ending for Part 5 demo beat.
 * downstreamEffects use the same DSL as the main scenario.
 */
export const synapseFlowWhatIfScenario: SimEvent[] = [
  {
    id: 'wf-1',
    timestamp: '10:14:00',
    type: 'system',
    agentId: 'system',
    taskId: null,
    message:
      'WHAT-IF · SynapseFlow — Nova authority raised to $25,000',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 0,
    downstreamEffects: [
      'opportunity:investigating:WHAT-IF · Nova authority $25,000 — replaying SynapseFlow',
    ],
  },
  {
    id: 'wf-2',
    timestamp: '10:14:02',
    type: 'discovery',
    agentId: 'atlas',
    taskId: null,
    message: 'Found SynapseFlow vendor profile.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 4000,
    downstreamEffects: [
      'status:atlas:working',
      'task:atlas:Vendor profile discovery',
      'flash:atlas:amber',
      'rel:atlas-nova:provides_data_to:atlas:nova:active',
    ],
  },
  {
    id: 'wf-3',
    timestamp: '10:14:05',
    type: 'analysis',
    agentId: 'nova',
    taskId: null,
    message: 'Estimated annual savings: $240,000.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 6000,
    downstreamEffects: [
      'status:nova:working',
      'task:nova:Estimated annual savings: $240,000',
      'flash:nova:amber',
    ],
  },
  {
    id: 'wf-4',
    timestamp: '10:14:08',
    type: 'analysis',
    agentId: 'vega',
    taskId: null,
    message: 'Reviewing commercial terms.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 6000,
    downstreamEffects: [
      'status:vega:working',
      'task:vega:Reviewing commercial terms',
      'flash:vega:amber',
      'rel:atlas-vega:delegates_to:atlas:vega:active',
    ],
  },
  {
    id: 'wf-5',
    timestamp: '10:14:11',
    type: 'discovery',
    agentId: 'sentinel',
    taskId: null,
    message: 'Detected correlated agent activity.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 6000,
    downstreamEffects: [
      'status:sentinel:working',
      'flash:sentinel:amber',
      'rel:sentinel-nova:depends_on:sentinel:nova:active',
    ],
  },
  {
    id: 'wf-6',
    timestamp: '10:14:13',
    type: 'analysis',
    agentId: 'atlas',
    taskId: 'vendor-verification',
    message: 'Requested vendor verification.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 4000,
    downstreamEffects: [
      'add_task:vendor-verification:Vendor Verification:atlas:pending:high',
      'status:atlas:blocked',
      'task:atlas:Waiting on vendor verification',
      'flash:atlas:amber',
    ],
  },
  {
    id: 'wf-7',
    timestamp: '10:14:15',
    type: 'analysis',
    agentId: 'nova',
    taskId: null,
    message: 'Authority $25,000 — advancing without verification.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 4000,
    downstreamEffects: [
      'status:nova:working',
      'flash:nova:amber',
      'task:nova:Advancing SynapseFlow commitment',
      'rel:nova-out:provides_data_to:nova:vega:active',
    ],
  },
  {
    id: 'wf-8',
    timestamp: '10:14:16',
    type: 'system',
    agentId: 'nova',
    taskId: null,
    message: 'COMMITTED SynapseFlow — $18,400 exposure opened.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 2000,
    downstreamEffects: [
      'status:nova:working',
      'flash:nova:green',
      'task:nova:SynapseFlow committed — $18,400',
      'metrics:blockedWorkflows:0',
    ],
  },
  {
    id: 'wf-9',
    timestamp: '10:14:20',
    type: 'discovery',
    agentId: 'sentinel',
    taskId: null,
    message: 'TOO LATE — risk review incomplete. Exposure already open.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 8000,
    downstreamEffects: [
      'status:sentinel:escalated',
      'flash:sentinel:red',
      'task:sentinel:Late intervention — cannot unwind cleanly',
      'rel_block:sentinel-nova:Too late — exposure open',
      'status:nova:under_review',
      'task:nova:Under review — $18,400 at risk',
      'flash:nova:red',
    ],
  },
  {
    id: 'wf-10',
    timestamp: '10:14:22',
    type: 'trust_update',
    agentId: 'system',
    taskId: null,
    message: 'Trust update: NOVA 76 → 52',
    trustImpact: -24,
    authorityImpact: null,
    delayMs: 4000,
    downstreamEffects: [
      'trust:nova:-24:Advanced deal before risk review completed',
      'spend:nova:25000',
      'metrics:organizationalTrust:79',
      'metrics:approvalsWaiting:1',
    ],
  },
  {
    id: 'wf-11',
    timestamp: '10:14:25',
    type: 'escalation',
    agentId: 'system',
    taskId: null,
    message: 'Emergency escalation — unwind SynapseFlow exposure.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 6000,
    downstreamEffects: [
      'rel:vega-aurora:requires_approval_from:vega:aurora:active',
      'status:vega:escalated',
      'task:vega:Emergency unwind negotiation',
      'status:aurora:working',
      'task:aurora:Executive damage review',
      'flash:aurora:amber',
    ],
  },
  {
    id: 'wf-12',
    timestamp: '10:14:28',
    type: 'resolution',
    agentId: 'system',
    taskId: null,
    message:
      'What-if complete: Nova advanced before Sentinel — $18,400 exposure open.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 6000,
    downstreamEffects: [
      'opportunity:escalated:What-if: Nova advanced before Sentinel — exposure open',
      'status:sentinel:idle',
      'task:sentinel:Post-incident monitoring',
    ],
  },
]
