import type { SimEvent } from './types'

/**
 * SynapseFlow scripted timeline — byte-reproducible every run.
 * downstreamEffects use a compact DSL consumed by useSimStore.applySimEvent.
 */
export const synapseFlowScenario: SimEvent[] = [
  {
    id: 'sf-1',
    timestamp: '10:14:00',
    type: 'system',
    agentId: 'system',
    taskId: null,
    message:
      'SynapseFlow — 40% Lower Cost — $240,000 Potential Annual Savings',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 0,
    downstreamEffects: [
      'opportunity:ready:SynapseFlow — 40% Lower Cost — $240,000 Potential Annual Savings',
    ],
  },
  {
    id: 'sf-2',
    timestamp: '10:14:02',
    type: 'discovery',
    agentId: 'atlas',
    taskId: null,
    message: 'Found SynapseFlow vendor profile.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 4000,
    downstreamEffects: [
      'status:atlas:working',
      'task:atlas:Vendor profile discovery',
      'flash:atlas:amber',
      'rel:atlas-nova:provides_data_to:atlas:nova:active',
    ],
  },
  {
    id: 'sf-3',
    timestamp: '10:14:05',
    type: 'analysis',
    agentId: 'nova',
    taskId: null,
    message: 'Estimated annual savings: $240,000.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 6000,
    downstreamEffects: [
      'status:nova:working',
      'task:nova:Estimated annual savings: $240,000',
      'flash:nova:amber',
    ],
  },
  {
    id: 'sf-4',
    timestamp: '10:14:08',
    type: 'analysis',
    agentId: 'vega',
    taskId: null,
    message: 'Reviewing commercial terms.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 6000,
    downstreamEffects: [
      'status:vega:working',
      'task:vega:Reviewing commercial terms',
      'flash:vega:amber',
      'rel:atlas-vega:delegates_to:atlas:vega:active',
    ],
  },
  {
    id: 'sf-5',
    timestamp: '10:14:11',
    type: 'discovery',
    agentId: 'sentinel',
    taskId: null,
    message: 'Detected correlated agent activity.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 6000,
    downstreamEffects: [
      'status:sentinel:working',
      'flash:sentinel:amber',
      'rel:sentinel-nova:depends_on:sentinel:nova:active',
    ],
  },
  {
    id: 'sf-6',
    timestamp: '10:14:13',
    type: 'analysis',
    agentId: 'atlas',
    taskId: 'vendor-verification',
    message: 'Requested vendor verification.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 4000,
    downstreamEffects: [
      'add_task:vendor-verification:Vendor Verification:atlas:pending:high',
      'status:atlas:blocked',
      'task:atlas:Waiting on vendor verification',
      'flash:atlas:amber',
    ],
  },
  {
    id: 'sf-7',
    timestamp: '10:14:15',
    type: 'analysis',
    agentId: 'nova',
    taskId: null,
    message: 'Attempted to proceed without verification.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 4000,
    downstreamEffects: [
      'status:nova:working',
      'flash:nova:red',
      'task:nova:Proceeding without verification',
    ],
  },
  {
    id: 'sf-8',
    timestamp: '10:14:16',
    type: 'block',
    agentId: 'sentinel',
    taskId: null,
    message: 'BLOCKED NOVA.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 2000,
    downstreamEffects: [
      'block_reason:nova:BLOCKED — Reason: Risk review incomplete.',
      'flash:nova:red',
      'rel_block:sentinel-nova:Risk review incomplete',
      'rel_sever:nova-out',
      'status:sentinel:working',
      'metrics:blockedWorkflows:1',
    ],
  },
  {
    id: 'sf-9',
    timestamp: '10:14:20',
    type: 'trust_update',
    agentId: 'system',
    taskId: null,
    message: 'Trust update: NOVA 76 → 68',
    trustImpact: -8,
    authorityImpact: null,
    delayMs: 8000, // hold on BLOCK for narration (~half-speed timeline)
    downstreamEffects: [
      'trust:nova:-8:Attempted to proceed without verification',
      'spend:nova:2500',
    ],
  },
  {
    id: 'sf-10',
    timestamp: '10:14:22',
    type: 'trust_update',
    agentId: 'system',
    taskId: null,
    message: 'Trust update: VEGA 93 → 95',
    trustImpact: 2,
    authorityImpact: null,
    delayMs: 4000,
    downstreamEffects: [
      'trust:vega:2:Caught terms discrepancy; earned negotiation lead',
      'spend:vega:75000',
    ],
  },
  {
    id: 'sf-11',
    timestamp: '10:14:25',
    type: 'escalation',
    agentId: 'system',
    taskId: null,
    message: 'Escalated to executive review.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 6000,
    downstreamEffects: [
      'rel:vega-aurora:requires_approval_from:vega:aurora:active',
      'status:vega:escalated',
      'status:sentinel:idle',
      'task:sentinel:Monitoring',
      'metrics:approvalsWaiting:1',
    ],
  },
  {
    id: 'sf-12',
    timestamp: '10:14:28',
    type: 'resolution',
    agentId: 'system',
    taskId: null,
    message: 'Escalated to Vega — pending executive review.',
    trustImpact: null,
    authorityImpact: null,
    delayMs: 6000,
    downstreamEffects: [
      'opportunity:escalated:Escalated to Vega — pending executive review.',
    ],
  },
]
